name: CI Pipeline for the Frontend

on:
  pull_request:
    types: [opened, review_requested, synchronize]

jobs:
  frontend:
    if: "!contains(github.event.pull_request.labels.*.name, 'ops') && !contains(github.head_ref, 'ops/')"
    strategy:
      matrix:
        node: ["18.14.1"]
        flavor: ["prod"]
      fail-fast: false
    runs-on: "ubuntu-latest"

    name: Frontend (${{ matrix.flavor }}) - node ${{ matrix.node }}
    steps:
      - name: Initialize Energy Estimation
        uses: green-coding-berlin/eco-ci-energy-estimation@v1
        with:
          task: start-measurement

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ${{ matrix.node }}/${{ matrix.flavor }}

      - name: Measure checkout
        uses: green-coding-berlin/eco-ci-energy-estimation@v1
        with:
            task: get-measurement
            label: 'Checkout'

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          registry-url: "https://registry.npmjs.org"
          
      - name: Measure node setup
        uses: green-coding-berlin/eco-ci-energy-estimation@v1
        with:
            task: get-measurement
            label: 'Node setup'

      - name: Install prod dependencies
        run: npm ci --omit=dev --omit=optional
        if: ${{ matrix.flavor == 'prod'}}
        working-directory: ${{ matrix.node }}/${{ matrix.flavor }}/frontend

      - name: Install dependencies
        if: ${{ matrix.flavor == 'dev'}}
        run: npm ci
        working-directory: ${{ matrix.node }}/${{ matrix.flavor }}/frontend

      - name: Measure install dependencies
        uses: green-coding-berlin/eco-ci-energy-estimation@v1
        with:
            task: get-measurement
            label: 'Install dependencies'

      - name: Lint
        if: ${{ matrix.flavor == 'dev'}}
        run: npm run lint
        working-directory: ${{ matrix.node }}/${{ matrix.flavor }}/frontend

      - name: Measure lint
        uses: green-coding-berlin/eco-ci-energy-estimation@v1
        with:
            task: get-measurement
            label: 'Lint'
            
      - name: DevSkim
        uses: microsoft/DevSkim-Action@v1
      
      - name: Upload DevSkim results
        uses: github/codeql-action/upload-sarif@v2
        with:
            sarif_file: devskim-results.sarif
      
      - name: Measure DevSkim
        uses: green-coding-berlin/eco-ci-energy-estimation@v1
        with:
            task: get-measurement
            label: 'DevSkim' 
            
      # - name: Test
      #   run: npm run test

      # - name: Measure test
      #   uses: green-coding-berlin/eco-ci-energy-estimation@v1
      #   with:
      #       task: get-measurement
      #       label: 'Test'

      - name: Build
        run: npm run build
        working-directory: ${{ matrix.node }}/${{ matrix.flavor }}/frontend

      - name: Measure build
        uses: green-coding-berlin/eco-ci-energy-estimation@v1
        with:
            task: get-measurement
            label: 'Build'

      - name: Show Energy Results
        uses: green-coding-berlin/eco-ci-energy-estimation@v1
        with:
          task: display-results
